package com.example.crud_hospital_pt2.model.enums;

public enum Specialty {
    CARDIOLOGY,
    DERMATOLOGY,
    GYNECOLOGY,
    OBSTETRICS,
    PEDIATRICS,
    PSYCHIATRY,
    ORTHOPEDICS,
    TRAUMATOLOGY,
    OPHTHALMOLOGY,
    NEUROLOGY,
    ONCOLOGY,
    PEDIATRIC_CARDIOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    HEMATOLOGY,
    INFECTIOUS_DISEASES,
    NEPHROLOGY,
    PNEUMOLOGY,
    UROLOGY,
    RADIOLOGY,
    ANESTHESIOLOGY,
    GENERAL_SURGERY,
    PLASTIC_SURGERY,
    INTERNAL_MEDICINE,
    GERIATRICS
}
